#
# Copyright 2024 The OKDP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: publish docker image into registry 

on:
  workflow_call:
    inputs:
      path:
        description: Package path
        required: false
        type: string
        default: 'docker'
      registry:
        description: Github released tag name
        required: false
        type: string
        default: 'quay.io'
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_ROBOT_TOKEN:
        required: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:

  latest-image-tag:
    runs-on: "ubuntu-latest"
    outputs:
      image: ${{ steps.latest-image-tag.outputs.image }}
      latest_tag: ${{ steps.latest-image-tag.outputs.latest_tag }}
      latest_git_tag: ${{ steps.latest-image-tag.outputs.latest_git_tag }}
    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Get latest GitHub Release tag name 📥
        id: latest-image-tag
        uses: okdp/gh-workflows/.github/actions/latest-image-tag@v1

  docker-image-publish:
    needs: [latest-image-tag]
    name: "Docker publish (${{ needs.latest-image-tag.outputs.image }}:${{ needs.latest-image-tag.outputs.latest_tag }})"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout release tag ${{ needs.latest-image-tag.outputs.latest_git_tag }} ⚡️
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          ref: ${{ needs.latest-image-tag.outputs.latest_git_tag }}

      ### Common steps between CI and Publish
      - name: Free up disk space 📦
        uses: okdp/gh-workflows/.github/actions/free-disk-space@v1

      - name: Set up QEMU and Docker Buildx 📦
        uses: okdp/gh-workflows/.github/actions/setup-buildx@v1

      - name: Set up container registry 📦
        id: registry
        env:
          INPUT_REGISTRY: ${{ inputs.registry }}
          VAR_REGISTRY: ${{ vars.REGISTRY }}
        run:  |
            registry="${VAR_REGISTRY:-$INPUT_REGISTRY}"
            echo "registry=$registry" >> "$GITHUB_OUTPUT"
            echo "registry_repo=${registry}/${GITHUB_REPOSITORY_OWNER@L}" >> "$GITHUB_OUTPUT"

      ### Publish steps
      ### The publish and periodic rebuilds are based on the latest stable github release tag
      - name: Login into ${{ steps.registry.outputs.registry }} registry 🔐
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ steps.registry.outputs.registry }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_ROBOT_TOKEN }}

      - name: Set image tags
        id: image-tags
        env:
          IMAGE: ${{ needs.latest-image-tag.outputs.image }}
          LATEST_TAG: ${{ needs.latest-image-tag.outputs.latest_tag }}
          REGISTRY_REPO: ${{ steps.registry.outputs.registry_repo }}
        run: |
           image_tag="$(echo "$LATEST_TAG" | awk -F- '{ print $1 }')"
           if [ "$image_tag" != "$LATEST_TAG" ]
           then
             image_tags="${REGISTRY_REPO}/${IMAGE}:${image_tag},"
           fi

           image_tags+="${REGISTRY_REPO}/${IMAGE}:${LATEST_TAG}"
           
           echo "tags=${image_tags}" >> "$GITHUB_OUTPUT"
           echo "Set image tags to: $image_tags"

      - name: Build and push to ${{ steps.registry.outputs.registry_repo }} repository 📤
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          file: ${{ inputs.path }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.image-tags.outputs.tags }}
          labels: |
            org.opencontainers.image.title="${{ needs.latest-image-tag.outputs.image }}"
            org.opencontainers.image.version="${{ needs.latest-image-tag.outputs.latest_tag }}"
            org.opencontainers.image.description="${{ needs.latest-image-tag.outputs.image }} image"
            org.opencontainers.image.source="https://github.com/${{ github.repository }}"
            org.opencontainers.image.licenses="Apache-2.0"
