#
# Copyright 2024 The OKDP Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: publish helm chart into oci registry

on:
  workflow_call:
    inputs:
      path:
        description: Package path
        required: true
        type: string
      chart_name:
        description: Helm chart version
        required: true
        type: string
      version:
        description: Helm chart version
        required: true
        type: string
      git_tag_name:
        description: Github released tag name
        required: true
        type: string
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_ROBOT_TOKEN:
        required: true
  
env:
  chart_package_name: ${{ inputs.chart_name }}-${{ inputs.version }}.tgz
  cr_release_name_template: "{{ .Name }}-v{{ .Version }}"

permissions:
  contents: read

defaults:
  run:
    shell: bash
  
jobs:

  helm-chart-publish:
    name: "Helm publish (${{ inputs.chart_name }}-${{ inputs.version }})"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: Checkout release tag ${{ inputs.git_tag_name }} ⚡️
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          ref: ${{ inputs.git_tag_name }}
      
      - name: Update release title
        env:
          CHART_NAME: ${{ inputs.chart_name }}
          GIT_TAG_NAME: ${{ inputs.git_tag_name }}
          GH_TOKEN: ${{ github.token }}
          VERSION: ${{ inputs.version }}
        run: |
          gh release edit "$GIT_TAG_NAME" --title="${CHART_NAME}-helm-chart-${VERSION}"

      - name: Setup helm 📦
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
        with:
          version: v3.15.1

      - name: Add chart dependencies 📦
        run: |
          helm repo add superset https://apache.github.io/superset
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Install chart-releaser (cr) 📦
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        with:
          install_only: true

      - name: Package helm chart ${{ inputs.path }} (${{ inputs.version }}) 📦
        env:
          CHART_PATH: ${{ inputs.path }}
        run: |
          helm dependency build "$CHART_PATH"
          cr package "$CHART_PATH"
    
      - name: Set up oci charts registry 📦
        id: registry
        env:
          VAR_REGISTRY: ${{ vars.REGISTRY }}
        run:  |
            registry="${VAR_REGISTRY:-quay.io}"
            echo "registry=$registry" >> "$GITHUB_OUTPUT"
            echo "registry_repo=${registry}/${GITHUB_REPOSITORY_OWNER@L}" >> "$GITHUB_OUTPUT"
     
      # More secure than helm registry login
      - name: Login into ${{ steps.registry.outputs.registry }} oci charts registry 🔐
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ steps.registry.outputs.registry }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_ROBOT_TOKEN }}

      # - name: Install Cosign 📦
      #   uses: sigstore/cosign-installer@v3.5.0

      # - name: Check cosign install! 📦
      #   run: cosign version

      - name: Push chart ${{ env.chart_package_name }} to oci registry  📤
        env:
          REGISTRY_REPO: ${{ steps.registry.outputs.registry_repo }}
        run: |
            helm push "./.cr-release-packages/${chart_package_name}" \
              "oci://${REGISTRY_REPO}/charts"

      - name: Upload Chart ${{ env.chart_package_name }} package to Github release  📤
        env:
          GIT_TAG_NAME: ${{ inputs.git_tag_name }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload "$GIT_TAG_NAME" "./.cr-release-packages/${chart_package_name}" --clobber

      # - name: Checkout gh-pages branch  ⚡️
      #   uses: actions/checkout@v6
      #   with:
      #     fetch-depth: 0
      #     ref: gh-pages
      #     path: gh-pages

      # - name: Update helm chart index.yaml
      #   run: |
      #     cr index  -i gh-pages/index.yaml \
      #               -r ${GITHUB_REPOSITORY#*/} \
      #               -o ${{ github.repository_owner }} \
      #               --release-name-template "${{ env.cr_release_name_template }}"
      #   shell: bash

      # - name: Commit helm chart index.yaml changes into gh-pages branch
      #   uses: EndBug/add-and-commit@v9
      #   with:
      #     cwd: gh-pages
      #     pull: "--rebase --autostash"
      #     message: '[${{ inputs.chart_name }}-${{ inputs.version }}] - Update index.yaml'
      #     author_name: github-actions[bot]
      #     author_email: 41898282+github-actions[bot]@users.noreply.github.com
